/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Health */
        get: operations["api_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sample Distribution
         * @description Sample from a statistical distribution and return histogram bins + summary
         *     stats. Gated by the shared API key (see src/main.py router mount).
         */
        post: operations["sample_distribution_stats_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Companies
         * @description Per-company signals for the latest snapshot (optionally one sector).
         */
        get: operations["get_companies_stocks_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/company/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company
         * @description One company's latest signal plus its history across every snapshot.
         */
        get: operations["get_company_stocks_company__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description A single run-level metric across every snapshot, for a trend chart.
         */
        get: operations["get_history_stocks_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Snapshot
         * @description Push an analysis snapshot into the stocks schema.
         *
         *     Idempotent: re-posting the same (as_of_date, label) upserts the run row
         *     and replaces every satellite row inside one transaction.
         */
        post: operations["ingest_snapshot_stocks_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest
         * @description Latest snapshot metadata, headline metrics, and the sector heatmap.
         */
        get: operations["get_latest_stocks_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/track-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Track Record
         * @description Realized walk-forward track record for the latest snapshot.
         */
        get: operations["get_track_record_stocks_track_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/bracket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bracket
         * @description Deterministic most-probable bracket (latest run by default).
         */
        get: operations["get_bracket_worldcup_bracket_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Per-team probability series across every archived snapshot.
         *
         *     Used by the UI's time-series chart. Snapshots are ordered chronologically;
         *     each point is `(as_of_date, value)` for the chosen stage.
         */
        get: operations["get_history_worldcup_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Snapshot
         * @description Push a prediction snapshot into the worldcup schema.
         *
         *     Idempotent: re-posting the same (tournament_key, as_of_date, label)
         *     upserts the run row and replaces every satellite row inside one
         *     transaction. Used both by the workstation primary path and the NAS
         *     fallback container.
         */
        post: operations["ingest_snapshot_worldcup_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest
         * @description Snapshot summary plus the full leaderboard (latest by default).
         */
        get: operations["get_latest_worldcup_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/played-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Played Matches
         * @description Locked group-stage results from the most recent snapshot.
         */
        get: operations["get_played_matches_worldcup_played_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/report-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Card
         * @description Walk-forward model evaluation for the selected run.
         */
        get: operations["get_report_card_worldcup_report_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/retrospective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Retrospective
         * @description Post-tournament wrap-up analysis for the selected run.
         */
        get: operations["get_retrospective_worldcup_retrospective_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worldcup/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenarios
         * @description What-if conditional championship odds for upcoming matches.
         */
        get: operations["get_scenarios_worldcup_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BracketResponse */
        BracketResponse: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Best Thirds */
            best_thirds: string[];
            /** Champion */
            champion: string;
            /** Final Pair */
            final_pair: string[];
            /** Group Winners */
            group_winners: {
                [key: string]: string[];
            };
            /** Match Details */
            match_details?: {
                [key: string]: components["schemas"]["MatchDetail-Output"][];
            } | null;
            /** Qf */
            qf: string[][];
            /** R16 */
            r16: string[][];
            /** R32 */
            r32: string[][];
            /** Run Id */
            run_id: number;
            /** Sf */
            sf: string[][];
            /** Tournament Key */
            tournament_key: string;
        };
        /** CompaniesResponse */
        CompaniesResponse: {
            /** Companies */
            companies: components["schemas"]["CompanyRow"][];
            run: components["schemas"]["src__endpoints__stocks__RunMeta"];
        };
        /** CompanyDetailResponse */
        CompanyDetailResponse: {
            /** History */
            history: components["schemas"]["CompanyHistoryPoint"][];
            latest: components["schemas"]["CompanyRow"];
            run: components["schemas"]["src__endpoints__stocks__RunMeta"];
        };
        /** CompanyHistoryPoint */
        CompanyHistoryPoint: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Exret 63 */
            exret_63: number | null;
            /** Label */
            label: string | null;
            /** Predicted Vol */
            predicted_vol: number | null;
            /** Sue */
            sue: number | null;
        };
        /** CompanyRow */
        CompanyRow: {
            /** Company Name */
            company_name: string | null;
            /** Exret 63 */
            exret_63: number | null;
            /** Filed */
            filed: string | null;
            /** Lag Days */
            lag_days: number | null;
            /** Ni Sue */
            ni_sue: number | null;
            /** Pre Vol */
            pre_vol: number | null;
            /** Predicted Vol */
            predicted_vol: number | null;
            /** Rev Sue */
            rev_sue: number | null;
            /** Sector */
            sector: string;
            /** Sue */
            sue: number | null;
            /** Sue Quintile */
            sue_quintile: number | null;
            /** Ticker */
            ticker: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramBin */
        HistogramBin: {
            /** Bin End */
            bin_end: number;
            /** Bin Start */
            bin_start: number;
            /** Count */
            count: number;
            /** Frequency */
            frequency: number;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Label */
            label: string | null;
            /** N Played Matches Locked */
            n_played_matches_locked: number;
            /** Value */
            value: number;
        };
        /** IngestBracket */
        IngestBracket: {
            /** Best Thirds */
            best_thirds: string[];
            /** Champion */
            champion: string;
            /** Final Pair */
            final_pair: string[];
            /** Group Winners */
            group_winners: {
                [key: string]: string[];
            };
            /** Match Details */
            match_details?: {
                [key: string]: components["schemas"]["MatchDetail-Input"][];
            } | null;
            /** Qf */
            qf: string[][];
            /** R16 */
            r16: string[][];
            /** R32 */
            r32: string[][];
            /** Sf */
            sf: string[][];
        };
        /** IngestCompany */
        IngestCompany: {
            /** Company Name */
            company_name?: string | null;
            /** Exret 63 */
            exret_63?: number | null;
            /** Filed */
            filed?: string | null;
            /** Lag Days */
            lag_days?: number | null;
            /** Ni Sue */
            ni_sue?: number | null;
            /** Pre Vol */
            pre_vol?: number | null;
            /** Predicted Vol */
            predicted_vol?: number | null;
            /** Rev Sue */
            rev_sue?: number | null;
            /** Sector */
            sector: string;
            /** Sue */
            sue?: number | null;
            /** Sue Quintile */
            sue_quintile?: number | null;
            /** Ticker */
            ticker: string;
        };
        /** IngestPlayedMatch */
        IngestPlayedMatch: {
            /** Away Score */
            away_score: number;
            /** Away Team */
            away_team: string;
            /** Group Name */
            group_name?: string | null;
            /** Home Score */
            home_score: number;
            /** Home Team */
            home_team: string;
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Rows Written */
            rows_written: {
                [key: string]: number;
            };
            /** Run Id */
            run_id: number;
        };
        /** IngestSector */
        IngestSector: {
            /** Mean Exret 63 */
            mean_exret_63?: number | null;
            /** Mean Predicted Vol */
            mean_predicted_vol?: number | null;
            /** Mean Sue */
            mean_sue?: number | null;
            /** N Names */
            n_names: number;
            /** Sector */
            sector: string;
            /** Sector Name */
            sector_name: string;
        };
        /** IngestTeamProb */
        IngestTeamProb: {
            /** Elo */
            elo: number;
            /** Final Pct */
            final_pct: number;
            /** Qf Pct */
            qf_pct: number;
            /** R16 Pct */
            r16_pct: number;
            /** R32 Pct */
            r32_pct: number;
            /** Sf Pct */
            sf_pct: number;
            /** Team */
            team: string;
            /** Winner Pct */
            winner_pct: number;
        };
        /** IngestTrackRecord */
        IngestTrackRecord: {
            /** Ic */
            ic?: number | null;
            /** Long Short Ret */
            long_short_ret?: number | null;
            /** N */
            n?: number | null;
            /** Period Label */
            period_label: string;
        };
        /**
         * MatchDetail
         * @description Per-match scoreline record. Predicted score always present (from the
         *     Poisson xG solver); actual_score + winner + went_to_penalties only
         *     populated for knockout matches that have been played.
         */
        "MatchDetail-Input": {
            /** Actual Score */
            actual_score?: number[] | null;
            /**
             * Played
             * @default false
             */
            played: boolean;
            /** Predicted Score */
            predicted_score: number[];
            /** Predicted Winner */
            predicted_winner?: string | null;
            /** Teams */
            teams: string[];
            /** Top Factors */
            top_factors?: components["schemas"]["TopFactor-Input"][] | null;
            /**
             * Went To Penalties
             * @default false
             */
            went_to_penalties: boolean;
            /** Winner */
            winner?: string | null;
        };
        /** MatchDetail */
        "MatchDetail-Output": {
            /** Actual Score */
            actual_score?: number[] | null;
            /**
             * Played
             * @default false
             */
            played: boolean;
            /** Predicted Score */
            predicted_score: number[];
            /** Predicted Winner */
            predicted_winner?: string | null;
            /** Teams */
            teams: string[];
            /** Top Factors */
            top_factors?: components["schemas"]["TopFactor-Output"][] | null;
            /**
             * Went To Penalties
             * @default false
             */
            went_to_penalties: boolean;
            /** Winner */
            winner?: string | null;
        };
        /** MetricPoint */
        MetricPoint: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Label */
            label: string | null;
            /** Value */
            value: number | null;
        };
        /** PlayedMatch */
        PlayedMatch: {
            /** Away Score */
            away_score: number;
            /** Away Team */
            away_team: string;
            /** Group Name */
            group_name: string | null;
            /** Home Score */
            home_score: number;
            /** Home Team */
            home_team: string;
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
        };
        /** PlayedMatchesResponse */
        PlayedMatchesResponse: {
            /** Matches */
            matches: components["schemas"]["PlayedMatch"][];
            run: components["schemas"]["src__endpoints__worldcup__RunMeta"];
        };
        /** ReportCardResponse */
        ReportCardResponse: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Report Card */
            report_card: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: number;
        };
        /** RetrospectiveResponse */
        RetrospectiveResponse: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Retrospective */
            retrospective: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: number;
        };
        /** SampleRequest */
        SampleRequest: {
            /**
             * Distribution
             * @enum {string}
             */
            distribution: "normal" | "uniform" | "exponential" | "beta" | "binomial" | "poisson";
            /**
             * N Bins
             * @default 40
             */
            n_bins: number;
            /**
             * N Samples
             * @default 1000
             */
            n_samples: number;
            /** Params */
            params: {
                [key: string]: number;
            };
        };
        /** SampleResponse */
        SampleResponse: {
            /** Distribution */
            distribution: string;
            /** Histogram */
            histogram: components["schemas"]["HistogramBin"][];
            /** N Samples */
            n_samples: number;
            /** Params */
            params: {
                [key: string]: number;
            };
            /** Stats */
            stats: {
                [key: string]: number;
            };
        };
        /** ScenariosResponse */
        ScenariosResponse: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Run Id */
            run_id: number;
            /** Scenarios */
            scenarios: {
                [key: string]: unknown;
            } | null;
        };
        /** SectorRow */
        SectorRow: {
            /** Mean Exret 63 */
            mean_exret_63: number | null;
            /** Mean Predicted Vol */
            mean_predicted_vol: number | null;
            /** Mean Sue */
            mean_sue: number | null;
            /** N Names */
            n_names: number;
            /** Sector */
            sector: string;
            /** Sector Name */
            sector_name: string;
        };
        /** TeamRow */
        TeamRow: {
            /** Elo */
            elo: number;
            /** Final Pct */
            final_pct: number;
            /** Qf Pct */
            qf_pct: number;
            /** R16 Pct */
            r16_pct: number;
            /** R32 Pct */
            r32_pct: number;
            /** Sf Pct */
            sf_pct: number;
            /** Team */
            team: string;
            /** Winner Pct */
            winner_pct: number;
        };
        /** TeamSeries */
        TeamSeries: {
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /** Team */
            team: string;
        };
        /**
         * TopFactor
         * @description One SHAP-derived contributor to the model's matchup prediction.
         *
         *     `impact` is the raw SHAP value on the predicted class from the base
         *     XGBoost model (calibrated probabilities preserve the ordering). `favors`
         *     names the team the feature pushed the prediction toward, or None on the
         *     rare draw prediction.
         */
        "TopFactor-Input": {
            /** Favors */
            favors?: string | null;
            /** Feature */
            feature: string;
            /** Impact */
            impact: number;
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** TopFactor */
        "TopFactor-Output": {
            /** Favors */
            favors?: string | null;
            /** Feature */
            feature: string;
            /** Impact */
            impact: number;
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** TrackRecordPoint */
        TrackRecordPoint: {
            /** Ic */
            ic: number | null;
            /** Long Short Ret */
            long_short_ret: number | null;
            /** N */
            n: number | null;
            /** Period Label */
            period_label: string;
        };
        /** TrackRecordResponse */
        TrackRecordResponse: {
            /** Points */
            points: components["schemas"]["TrackRecordPoint"][];
            run: components["schemas"]["src__endpoints__stocks__RunMeta"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** HistoryResponse */
        src__endpoints__stocks__HistoryResponse: {
            /** Metric */
            metric: string;
            /** Points */
            points: components["schemas"]["MetricPoint"][];
        };
        /** LatestResponse */
        src__endpoints__stocks__LatestResponse: {
            run: components["schemas"]["src__endpoints__stocks__RunMeta"];
            /** Sectors */
            sectors: components["schemas"]["SectorRow"][];
        };
        /** RunMeta */
        src__endpoints__stocks__RunMeta: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** N Events */
            n_events: number;
            /**
             * Run Timestamp Utc
             * Format: date-time
             */
            run_timestamp_utc: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Universe Size */
            universe_size: number;
        };
        /** IngestPayload */
        src__endpoints__stocks_admin__IngestPayload: {
            /** Companies */
            companies: components["schemas"]["IngestCompany"][];
            meta: components["schemas"]["src__endpoints__stocks_admin__IngestRunMeta"];
            /**
             * Sectors
             * @default []
             */
            sectors: components["schemas"]["IngestSector"][];
            /**
             * Track Record
             * @default []
             */
            track_record: components["schemas"]["IngestTrackRecord"][];
        };
        /** IngestRunMeta */
        src__endpoints__stocks_admin__IngestRunMeta: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Label */
            label?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: unknown;
            };
            /** N Events */
            n_events: number;
            /**
             * Run Timestamp Utc
             * Format: date-time
             */
            run_timestamp_utc: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Universe Size */
            universe_size: number;
        };
        /** HistoryResponse */
        src__endpoints__worldcup__HistoryResponse: {
            /** Series */
            series: components["schemas"]["TeamSeries"][];
            /** Stage */
            stage: string;
            /** Tournament Key */
            tournament_key: string;
        };
        /** LatestResponse */
        src__endpoints__worldcup__LatestResponse: {
            /** Leaderboard */
            leaderboard: components["schemas"]["TeamRow"][];
            run: components["schemas"]["src__endpoints__worldcup__RunMeta"];
        };
        /** RunMeta */
        src__endpoints__worldcup__RunMeta: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** N Played Matches Locked */
            n_played_matches_locked: number;
            /** N Simulations */
            n_simulations: number;
            /**
             * Run Timestamp Utc
             * Format: date-time
             */
            run_timestamp_utc: string;
            /** Tournament Key */
            tournament_key: string;
        };
        /** IngestPayload */
        src__endpoints__worldcup_admin__IngestPayload: {
            bracket: components["schemas"]["IngestBracket"];
            meta: components["schemas"]["src__endpoints__worldcup_admin__IngestRunMeta"];
            /**
             * Played Matches
             * @default []
             */
            played_matches: components["schemas"]["IngestPlayedMatch"][];
            /** Team Probabilities */
            team_probabilities: components["schemas"]["IngestTeamProb"][];
        };
        /** IngestRunMeta */
        src__endpoints__worldcup_admin__IngestRunMeta: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Label */
            label?: string | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /** N Played Matches Locked */
            n_played_matches_locked: number;
            /** N Simulations */
            n_simulations: number;
            /**
             * Run Timestamp Utc
             * Format: date-time
             */
            run_timestamp_utc: string;
            /**
             * Tournament Key
             * @default 2026
             */
            tournament_key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sample_distribution_stats_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companies_stocks_companies_get: {
        parameters: {
            query?: {
                /** @description Filter to one sector ETF code */
                sector?: string | null;
                limit?: number;
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_stocks_company__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_stocks_history_get: {
        parameters: {
            query?: {
                /** @description Run-level metric key */
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["src__endpoints__stocks__HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_snapshot_stocks_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["src__endpoints__stocks_admin__IngestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_stocks_latest_get: {
        parameters: {
            query?: {
                /** @description Pin to a specific snapshot date instead of the latest */
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["src__endpoints__stocks__LatestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_record_stocks_track_record_get: {
        parameters: {
            query?: {
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bracket_worldcup_bracket_get: {
        parameters: {
            query?: {
                tournament?: string;
                /** @description Pin to a specific snapshot date instead of the latest */
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BracketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_worldcup_history_get: {
        parameters: {
            query?: {
                tournament?: string;
                /** @description Which probability column to return */
                stage?: "winner" | "final" | "sf" | "qf" | "r16" | "r32";
                /** @description Comma-separated team names. If omitted, returns the top 10 teams by latest winner_pct. */
                teams?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["src__endpoints__worldcup__HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_snapshot_worldcup_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["src__endpoints__worldcup_admin__IngestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_worldcup_latest_get: {
        parameters: {
            query?: {
                /** @description Tournament key */
                tournament?: string;
                /** @description Top-N teams to return */
                limit?: number;
                /** @description Pin to a specific snapshot date instead of the latest */
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["src__endpoints__worldcup__LatestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_played_matches_worldcup_played_matches_get: {
        parameters: {
            query?: {
                tournament?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayedMatchesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_card_worldcup_report_card_get: {
        parameters: {
            query?: {
                tournament?: string;
                /** @description Pin to a specific snapshot date instead of the latest */
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retrospective_worldcup_retrospective_get: {
        parameters: {
            query?: {
                tournament?: string;
                /** @description Pin to a specific snapshot date instead of the latest */
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrospectiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_worldcup_scenarios_get: {
        parameters: {
            query?: {
                tournament?: string;
                /** @description Pin to a specific snapshot date instead of the latest */
                as_of_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
