name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test the app
        run: |
          yarn
          yarn test --browsers=ChromeHeadlessNoSandbox --watch=false
      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "Bishal Regmi"
          sed -i "s|%%REPLACE_ME%%|$API_URL|g" src/environments/environment.prod.ts
          yarn run ng deploy --base-href="https://regmibishal1.github.io/ResearchPortfolio-UI/" --name="regmibishal1" --email="$EMAIL"
